# Generated by Django 4.0.6 on 2022-09-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemblog', '0006_comment_voter_post_voter_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
