# Generated by Django 4.0.6 on 2022-09-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemblog', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
